server:
  port: 4001

spring:
  application:
    name: pig-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
        #git:
         # uri: https://gitee.com/king462755472/pig-config
         # default-label: ${spring.profiles.active}   #解决监控down11234

# 关闭安全管理
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
---
spring:
  profiles: dev
  rabbitmq:
    host: 47.107.243.232
    port: 5672
    username: test
    password: test
eureka:
  instance:
    prefer-ip-address: true
    #ip-address: 47.102.100.106
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1026/eureka
    registry-fetch-interval-seconds: 10
---
spring:
  profiles: prd
  rabbitmq:
    host: 47.107.243.232
    port: 5672
    username: test
    password: test
  cloud:
    config:
      retry:
        initial-interval: 3000
        multiplier: 1.5
        max-interval: 20000
        max-attempts: 6
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@eureka:1026/eureka
